//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MementoConnection.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MementoConnection.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 id,State,IsChecked,ResNumber,uid,Source,Channel,ChannelLanguage,Deposit,Subtotal,Balance,Commission,BookedDateTime,ArrivalDate,DepartureDate,ArrivalTime,Persons,Nights,Rooms,Comments,Status,LastChangedDateTime,RecordedDateTime,lid,CancelledDateTime 的本地化字符串。
        /// </summary>
        public static string ELiteResItemString {
            get {
                return ResourceManager.GetString("ELiteResItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,RID,ResNumber,uid,Type,ReservedDate,ArrivalDate,DepartureDate,Price,Persons,Rooms,Nights,Status 的本地化字符串。
        /// </summary>
        public static string ELiteResRoomItemString {
            get {
                return ResourceManager.GetString("ELiteResRoomItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,RID,Type,Floor,Building,HasTV,HasBathroom,HasToilet,IsDorm,Owner 的本地化字符串。
        /// </summary>
        public static string ELiteRoomItemString {
            get {
                return ResourceManager.GetString("ELiteRoomItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 id,uid,FullName,SurName,MiddleName,GivenName,Country,Email,Phone,Identity,PreferredLanguage,Address 的本地化字符串。
        /// </summary>
        public static string ELiteUserItemString {
            get {
                return ResourceManager.GetString("ELiteUserItemString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CREATE TABLE [log_staff](
        ///  [id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, 
        ///  [sid] INT NOT NULL, 
        ///  [RecordedDateTime] DATETIME NOT NULL DEFAULT (DATETIME (&apos;now&apos;, &apos;localtime&apos;))) 的本地化字符串。
        /// </summary>
        public static string StringCreateLogTableStaff {
            get {
                return ResourceManager.GetString("StringCreateLogTableStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info_res 的本地化字符串。
        /// </summary>
        public static string TableName_Res {
            get {
                return ResourceManager.GetString("TableName_Res", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info_res_rooms 的本地化字符串。
        /// </summary>
        public static string TableName_ResRoom {
            get {
                return ResourceManager.GetString("TableName_ResRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info_room 的本地化字符串。
        /// </summary>
        public static string TableName_Room {
            get {
                return ResourceManager.GetString("TableName_Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 info_user 的本地化字符串。
        /// </summary>
        public static string TableName_User {
            get {
                return ResourceManager.GetString("TableName_User", resourceCulture);
            }
        }
    }
}
